// TOPIK I Vocabulary - 1671 words extracted from TOPIK-I-1671.pdf
export interface VocabularyEntry {
  korean: string;
  english: string;
}

export const vocabularyData: VocabularyEntry[] = [
  { korean: '가게', english: 'store, shop' },
  { korean: '가격', english: 'price' },
  { korean: '가구', english: 'furniture' },
  { korean: '가깝다', english: 'close' },
  { korean: '가끔', english: 'sometimes' },
  { korean: '가다', english: 'go' },
  { korean: '가르치다', english: 'teach' },
  { korean: '가방', english: 'bag' },
  { korean: '가볍다', english: 'light' },
  { korean: '가수', english: 'singer' },
  { korean: '가슴', english: 'chest, breast' },
  { korean: '가요', english: 'song' },
  { korean: '가운데', english: 'middle' },
  { korean: '가위', english: 'scissors' },
  { korean: '가을', english: 'autumn, fall' },
  { korean: '가장', english: 'most' },
  { korean: '가져가다', english: 'take away' },
  { korean: '가져오다', english: 'bring' },
  { korean: '가족', english: 'family' },
  { korean: '가지', english: 'branch' },
  { korean: '가지다', english: 'have' },
  { korean: '각', english: 'each' },
  { korean: '간', english: 'while' },
  { korean: '간단하다', english: 'simple, easy' },
  { korean: '간단히', english: 'simply' },
  { korean: '간식', english: 'snack' },
  { korean: '간장', english: 'soy sauce' },
  { korean: '간호사', english: 'nurse' },
  { korean: '갈비', english: 'Galvi, spareribs' },
  { korean: '갈비탕', english: 'Galbitang, spareribs soup' },
  { korean: '갈색', english: 'brown' },
  { korean: '갈아타다', english: 'transfer' },
  { korean: '감', english: 'persimmon' },
  { korean: '감기', english: 'cold' },
  { korean: '감기약', english: 'cold medicine' },
  { korean: '감다', english: 'close ~ (eyes)' },
  { korean: '감동', english: 'sensation' },
  { korean: '감동하다', english: 'be impressed' },
  { korean: '감사', english: 'thank' },
  { korean: '감사드립니다', english: 'thank you' },
  { korean: '감사하다', english: 'thank, appreciate' },
  { korean: '감사합니다', english: 'thank you' },
  { korean: '감자', english: 'potato' },
  { korean: '감자탕', english: 'Gamjatang, potato soup' },
  { korean: '갑자기', english: 'suddenly' },
  { korean: '값', english: 'price' },
  { korean: '강', english: 'river' },
  { korean: '강아지', english: 'puppy' },
  { korean: '강좌', english: 'lecture' },
  { korean: '갖다', english: 'have' },
  { korean: '같다', english: 'same' },
  { korean: '같이', english: 'together' },
  { korean: '개', english: 'dog, ~ piece(s)' },
  { korean: '개나리', english: 'forsythia' },
  { korean: '개인', english: 'individual' },
  { korean: '거기', english: 'there' },
  { korean: '거리', english: 'street' },
  { korean: '거실', english: 'living room' },
  { korean: '거울', english: 'mirror' },
  { korean: '거의', english: 'almost, nearly' },
  { korean: '거짓말', english: 'lie' },
  { korean: '걱정', english: 'anxiety, concern' },
  { korean: '걱정하다', english: 'worry' },
  { korean: '건강', english: 'health' },
  { korean: '건강하다', english: 'be healthy' },
  { korean: '건너가다', english: 'cross (a road)' },
  { korean: '건너다', english: 'cross over' },
  { korean: '건너편', english: 'other side, opposite side' },
  { korean: '건물', english: 'building' },
  { korean: '건배', english: 'cheers, toast' },
  { korean: '걷다', english: 'walk' },
  { korean: '걸다', english: 'bet, call' },
  { korean: '걸리다', english: 'get caught, take (time)' },
  { korean: '걸어가다', english: 'walk (go)' },
  { korean: '걸어오다', english: 'walk (come)' },
  { korean: '검은색', english: 'black' },
  { korean: '것', english: 'that, thing, it' },
  { korean: '게임', english: 'game' },
  { korean: '겨울', english: 'winter' },
  { korean: '겨울방학', english: 'winter vacation' },
  { korean: '결과', english: 'result' },
  { korean: '결정', english: 'decision' },
  { korean: '결정하다', english: 'decide' },
  { korean: '결혼', english: 'marriage' },
  { korean: '결혼식', english: 'wedding ceremony' },
  { korean: '결혼하다', english: 'get married' },
  { korean: '경기', english: 'competition, game' },
  { korean: '경기장', english: 'stadium, arena' },
  { korean: '경복궁', english: 'Gyeongbokgung' },
  { korean: '경주', english: 'Gyeongju' },
  { korean: '경찰', english: 'police' },
  { korean: '경찰관', english: 'police officer' },
  { korean: '경찰서', english: 'police office' },
  { korean: '경치', english: 'view, landscape' },
  { korean: '경험', english: 'experience' },
  { korean: '계단', english: 'stairs' },
  { korean: '계란', english: 'egg' },
  { korean: '계산하다', english: 'calculate' },
  { korean: '계속', english: 'continue' },
  { korean: '계시다', english: 'be, exist (honorific form)' },
  { korean: '계절', english: 'season' },
  { korean: '계획', english: 'plan' },
  { korean: '고기', english: 'meat' },
  { korean: '고등학교', english: 'high school' },
  { korean: '고등학생', english: 'high school student' },
  { korean: '고르다', english: 'choose' },
  { korean: '고마웠습니다', english: 'Thank you (past tense)' },
  { korean: '고맙다', english: 'thank' },
  { korean: '고맙습니다', english: 'Thank you' },
  { korean: '고모', english: 'paternal aunt' },
  { korean: '고모부', english: 'paternal uncle' },
  { korean: '고속버스', english: 'express bus' },
  { korean: '고양이', english: 'cat' },
  { korean: '고장', english: 'broken, malfunction' },
  { korean: '고추', english: 'red pepper' },
  { korean: '고추장', english: 'Kochujang, red pepper paste' },
  { korean: '고치다', english: 'fix' },
  { korean: '고프다', english: 'hungry' },
  { korean: '고향', english: 'hometown' },
  { korean: '곧', english: 'soon' },
  { korean: '골목', english: 'alley' },
  { korean: '골프', english: 'golf' },
  { korean: '곱다', english: 'beautiful' },
  { korean: '곳', english: 'place' },
  { korean: '공', english: 'ball' },
  { korean: '공간', english: 'space' },
  { korean: '공기', english: 'air' },
  { korean: '공무원', english: 'public official' },
  { korean: '공부', english: 'study' },
  { korean: '공부하다', english: 'study' },
  { korean: '공연', english: 'show, public performance' },
  { korean: '공원', english: 'park' },
  { korean: '공중전화', english: 'payphone, public phone' },
  { korean: '공짜', english: 'free' },
  { korean: '공책', english: 'notebook, note' },
  { korean: '공항', english: 'airport' },
  { korean: '공휴일', english: 'public holiday' },
  { korean: '과', english: 'division' },
  { korean: '과거', english: 'past' },
  { korean: '과일', english: 'fruit' },
  { korean: '과자', english: 'snack' },
  { korean: '과학', english: 'science' },
  { korean: '관계', english: 'relation' },
  { korean: '관광하다', english: 'travel, sightsee' },
  { korean: '관심', english: 'attention, interest' },
  { korean: '광고', english: 'advertisement' },
  { korean: '괜찮다', english: 'be okay' },
  { korean: '괜찮습니다', english: "It's fine." },
  { korean: '교과서', english: 'textbook' },
  { korean: '교수', english: 'professor' },
  { korean: '교실', english: 'classroom' },
  { korean: '교체', english: 'substitute, change' },
  { korean: '교통', english: 'traffic' },
  { korean: '교통사고', english: 'traffic accident' },
  { korean: '교회', english: 'church' },
  { korean: '구', english: '9' },
  { korean: '구경하다', english: 'take a look' },
  { korean: '구두', english: 'shoes' },
  { korean: '구름', english: 'cloud' },
  { korean: '구십', english: '90' },
  { korean: '구월', english: 'September' },
  { korean: '구하다', english: 'save, seek, get' },
  { korean: '국', english: 'soup' },
  { korean: '국내', english: 'domestic' },
  { korean: '국립', english: 'nationalestablished, state' },
  { korean: '국수', english: 'noodle' },
  { korean: '국어', english: 'Korean language' },
  { korean: '국적', english: 'nationality, country of citizenship' },
  { korean: '국제', english: 'international' },
  { korean: '군인', english: 'soldier, military personnel' },
  { korean: '굽다', english: 'bake' },
  { korean: '권', english: '~ book(s)' },
  { korean: '귀', english: 'ear' },
  { korean: '귀엽다', english: 'cute' },
  { korean: '규칙', english: 'rule' },
  { korean: '귤', english: 'mandarin orange' },
  { korean: '그', english: 'it' },
  { korean: '그거', english: 'it' },
  { korean: '그것', english: 'it' },
  { korean: '그곳', english: 'there' },
  { korean: '그날', english: 'that day' },
  { korean: '그냥', english: 'just, as it is' },
  { korean: '그동안', english: 'meantime, meanwhile, up to now' },
  { korean: '그들', english: 'them, they' },
  { korean: '그때', english: 'then, at that time' },
  { korean: '그래', english: 'Yes, Yeah' },
  { korean: '그래서', english: 'so, thus' },
  { korean: '그램', english: 'gram' },
  { korean: '그러나', english: 'but, however' },
  { korean: '그러니까', english: 'so, because' },
  { korean: '그러면', english: 'then, if so' },
  { korean: '그런', english: 'then, such' },
  { korean: '그런데', english: 'by the way, however' },
  { korean: '그럼', english: 'then' },
  { korean: '그렇게', english: 'like that, so' },
  { korean: '그렇구나', english: 'well, I see.' },
  { korean: '그렇다', english: "Yes, that's it." },
  { korean: '그렇습니다', english: "That's right." },
  { korean: '그렇지만', english: 'nevertheless, but' },
  { korean: '그릇', english: 'bowl, container, tableware' },
  { korean: '그리고', english: 'and' },
  { korean: '그리다', english: 'draw' },
  { korean: '그림', english: 'drawing, picture' },
  { korean: '그만', english: 'stop, finish' },
  { korean: '그분', english: 'his, the person' },
  { korean: '그저께', english: 'day before yesterday' },
  { korean: '그중', english: 'among them' },
  { korean: '그쪽', english: 'there, the person' },
  { korean: '그치다', english: 'stop, end, cease' },
  { korean: '극장', english: 'theater, cinema' },
  { korean: '근처', english: 'nearby, neighborhood' },
  { korean: '글', english: 'post, sentence, character' },
  { korean: '글쎄요', english: 'I do not know., well, I guess ~' },
  { korean: '금방', english: 'soon, a little while ago' },
  { korean: '금연', english: 'no smoking' },
  { korean: '금요일', english: 'Friday' },
  { korean: '금주', english: 'abstinence, temperance' },
  { korean: '급', english: 'class, grade' },
  { korean: '급하다', english: 'hurry, urgent' },
  { korean: '기간', english: 'term, period' },
  { korean: '기다리다', english: 'wait' },
  { korean: '기르다', english: 'cultivate, grow' },
  { korean: '기름', english: 'oil, gasoline' },
  { korean: '기분', english: 'feeling' },
  { korean: '기뻐하다', english: 'glad, delight' },
  { korean: '기쁘다', english: 'happy' },
  { korean: '기사', english: 'article, driver, engineer' },
  { korean: '기숙사', english: 'dormitory' },
  { korean: '기억하다', english: 'remember' },
  { korean: '기온', english: 'temperature' },
  { korean: '기자', english: 'reporter' },
  { korean: '기차', english: 'train' },
  { korean: '기침', english: 'cough' },
  { korean: '기타', english: 'other' },
  { korean: '긴장되다', english: 'be nervous' },
  { korean: '길', english: 'way, road' },
  { korean: '길다', english: 'long' },
  { korean: '김', english: 'seaweed' },
  { korean: '김밥', english: 'Kimbab' },
  { korean: '김치', english: 'Kimchi' },
  { korean: '김치찌개', english: 'Kimchi stew' },
  { korean: '김포공항', english: 'Gimpo International Airport' },
  { korean: '까만색', english: 'black color' },
  { korean: '까맣다', english: 'black' },
  { korean: '깎다', english: 'cut, shave' },
  { korean: '깜짝', english: 'startled, surprised' },
  { korean: '깨끗하다', english: 'clean' },
  { korean: '깨다', english: 'wake up, crack, break' },
  { korean: '깨지다', english: 'chip, crack, break' },
  { korean: '꺼내다', english: 'take out' },
  { korean: '껌', english: 'chewing gum' },
  { korean: '꼭', english: 'exactly, absolutely' },
  { korean: '꽃', english: 'flower' },
  { korean: '꽃집', english: 'florist' },
  { korean: '꾸다', english: 'dream' },
  { korean: '꿈', english: 'dream' },
  { korean: '끄다', english: 'turn off, extinguish, stop' },
  { korean: '끓이다', english: 'boil' },
  { korean: '끝', english: 'end' },
  { korean: '끝나다', english: 'finish, end' },
  { korean: '끝내다', english: 'finish' },
  { korean: '끼다', english: 'put on, plug, (fog) rolls in' },
  { korean: '나', english: 'I' },
  { korean: '나가다', english: 'go out, get out' },
  { korean: '나누다', english: 'share, divide' },
  { korean: '나다', english: 'occur, come out' },
  { korean: '나라', english: 'country' },
  { korean: '나무', english: 'tree' },
  { korean: '나빠지다', english: 'spoil, deteriorate' },
  { korean: '나쁘다', english: 'bad' },
  { korean: '나오다', english: 'come out, appear' },
  { korean: '나이', english: 'age, old' },
  { korean: '나중', english: 'later, after' },
  { korean: '나타나다', english: 'appear' },
  { korean: '나흘', english: 'four days' },
  { korean: '낚시', english: 'fishing' },
  { korean: '날', english: 'day' },
  { korean: '날씨', english: 'weather' },
  { korean: '날짜', english: 'date' },
  { korean: '남', english: 'south, man' },
  { korean: '남기다', english: 'leave' },
  { korean: '남녀', english: 'men and women' },
  { korean: '남대문시장', english: 'Namdaemun market' },
  { korean: '남동생', english: 'younger brother' },
  { korean: '남미', english: 'South America' },
  { korean: '남북', english: 'north and south' },
  { korean: '남자', english: 'man' },
  { korean: '남쪽', english: 'south' },
  { korean: '남편', english: 'husband' },
  { korean: '남학생', english: 'male student' },
  { korean: '낮', english: 'day, noon, during the day' },
  { korean: '낮다', english: 'low' },
  { korean: '내', english: 'of mine, my' },
  { korean: '내가', english: 'I' },
  { korean: '내과', english: 'internal medicine' },
  { korean: '내년', english: 'next year' },
  { korean: '내다', english: 'pay, put out' },
  { korean: '내려가다', english: 'go down' },
  { korean: '내려오다', english: 'come down' },
  { korean: '내리다', english: 'go down' },
  { korean: '내용', english: 'content' },
  { korean: '내일', english: 'tomorrow' },
  { korean: '냄비', english: 'pot' },
  { korean: '냄새', english: 'smell' },
  { korean: '냉면', english: 'cold noodle' },
  { korean: '냉장고', english: 'refrigerator' },
  { korean: '너', english: 'you' },
  { korean: '너무', english: 'too, very' },
  { korean: '넓다', english: 'wide' },
  { korean: '넘다', english: 'exceed, more than' },
  { korean: '넘어지다', english: 'fall down, fall' },
  { korean: '넣다', english: 'put in' },
  { korean: '네', english: 'yes, 4' },
  { korean: '넥타이', english: 'necktie' },
  { korean: '넷', english: '4' },
  { korean: '넷째', english: 'fourth' },
  { korean: '년', english: 'year' },
  { korean: '노란색', english: 'yellow color' },
  { korean: '노랗다', english: 'yellow' },
  { korean: '노래', english: 'song' },
  { korean: '노래방', english: 'Karaoke shop' },
  { korean: '노래하다', english: 'sing' },
  { korean: '노력하다', english: 'endeavor, strive' },
  { korean: '노트', english: 'note' },
  { korean: '녹색', english: 'green' },
  { korean: '녹차', english: 'green tea' },
  { korean: '놀다', english: 'play' },
  { korean: '놀라다', english: 'be surprised' },
  { korean: '농구', english: 'basketball' },
  { korean: '높다', english: 'high' },
  { korean: '놓다', english: 'put' },
  { korean: '누가', english: 'who' },
  { korean: '누구', english: 'who' },
  { korean: '누나', english: 'sister (as seen from the younger brother)' },
  { korean: '누르다', english: 'press down, push' },
  { korean: '눈', english: 'eye, snow' },
  { korean: '눈물', english: 'tear' },
  { korean: '눈사람', english: 'snowman' },
  { korean: '눈싸움', english: 'staring contest, snowball fight' },
  { korean: '눕다', english: 'lie down, sleep' },
  { korean: '뉴스', english: 'news' },
  { korean: '뉴욕', english: 'New York' },
  { korean: '느끼다', english: 'feel' },
  { korean: '느낌', english: 'feeling' },
  { korean: '느리다', english: 'slow' },
  { korean: '늘', english: 'always' },
  { korean: '늘다', english: 'gain, increase' },
  { korean: '능력', english: 'ability' },
  { korean: '늦다', english: 'late, delay' },
  { korean: '늦잠', english: 'overslept, sleeping in late' },
  { korean: '님', english: 'Sir' },
  { korean: '다', english: 'all, whole' },
  { korean: '다녀오다', english: 'return, come back' },
  { korean: '다니다', english: 'go, commute' },
  { korean: '다르다', english: 'different' },
  { korean: '다른', english: 'other ~, another ~, different ~' },
  { korean: '다리', english: 'bridge, leg, foot' },
  { korean: '다섯', english: '5' },
  { korean: '다시', english: 'again' },
  { korean: '다음', english: 'next, after' },
  { korean: '다음달', english: 'next month' },
  { korean: '다음주', english: 'next week' },
  { korean: '다음해', english: 'next year, following year' },
  { korean: '다이어트', english: 'diet' },
  { korean: '다치다', english: 'hurt' },
  { korean: '닦다', english: 'wipe, polish' },
  { korean: '단어', english: 'word' },
  { korean: '단점', english: 'disadvantage, shortcoming, drawback' },
  { korean: '닫다', english: 'close' },
  { korean: '닫히다', english: 'shut, close' },
  { korean: '달', english: 'month, moon' },
  { korean: '달걀', english: 'egg' },
  { korean: '달다', english: 'sweet' },
  { korean: '달러', english: 'dollar' },
  { korean: '달력', english: 'calendar' },
  { korean: '달리다', english: 'run' },
  { korean: '닭', english: 'chicken, hen' },
  { korean: '닭고기', english: 'chicken' },
  { korean: '닮다', english: 'resemble' },
  { korean: '담그다', english: 'dip, pickle' },
  { korean: '담배', english: 'tobacco' },
  { korean: '답장', english: 'reply' },
  { korean: '당근', english: 'carrot' },
  { korean: '당신', english: 'you' },
  { korean: '대', english: 'versus, large' },
  { korean: '대답', english: 'answer' },
  { korean: '대답하다', english: 'answer, reply' },
  { korean: '대부분', english: 'mostly, almost' },
  { korean: '대사관', english: 'embassy' },
  { korean: '대학', english: 'university, college' },
  { korean: '대학교', english: 'university, college' },
  { korean: '대학생', english: 'college student' },
  { korean: '대학원', english: 'graduate school' },
  { korean: '대학원생', english: 'postgraduate student, graduate student' },
  { korean: '대한민국', english: 'Republic of Korea, South Korea' },
  { korean: '대화', english: 'conversation, dialogue' },
  { korean: '대회', english: 'competition, tournament' },
  { korean: '댁', english: 'house' },
  { korean: '더', english: 'more' },
  { korean: '더럽다', english: 'dirty' },
  { korean: '더운물', english: 'hot water' },
  { korean: '덕분', english: 'thanks for, thanks to' },
  { korean: '덥다', english: 'hot' },
  { korean: '덮다', english: 'cover' },
  { korean: '데리다', english: 'bring, take along' },
  { korean: '데이트', english: 'date, dating' },
  { korean: '도로', english: 'road' },
  { korean: '도서관', english: 'library' },
  { korean: '도시', english: 'city' },
  { korean: '도와주다', english: 'help' },
  { korean: '도움', english: 'help, assistance' },
  { korean: '도착', english: 'arrival' },
  { korean: '도착하다', english: 'arrive' },
  { korean: '도쿄', english: 'Tokyo' },
  { korean: '독서', english: 'reading' },
  { korean: '독서실', english: 'reading room' },
  { korean: '독서하다', english: 'read' },
  { korean: '독일', english: 'Germany' },
  { korean: '돈', english: 'money' },
  { korean: '돌아가다', english: 'return, go back' },
  { korean: '돌아오다', english: 'come back, come home' },
  { korean: '돕다', english: 'help' },
  { korean: '동네', english: 'town, neighborhood' },
  { korean: '동대문시장', english: 'Dongdaemun market' },
  { korean: '동물', english: 'animal' },
  { korean: '동생', english: 'brother, sister' },
  { korean: '동아리', english: 'club, group' },
  { korean: '동안', english: 'during, between' },
  { korean: '동양', english: 'eastern, orient' },
  { korean: '동전', english: 'coin' },
  { korean: '동쪽', english: 'east' },
  { korean: '돼지', english: 'pig' },
  { korean: '돼지고기', english: 'pork' },
  { korean: '되다', english: 'become' },
  { korean: '된장', english: 'fermented soybean paste' },
  { korean: '된장국', english: 'soybean paste soup' },
  { korean: '된장찌개', english: 'soybean paste stew' },
  { korean: '두', english: 'two' },
  { korean: '두껍다', english: 'thick' },
  { korean: '두다', english: 'put' },
  { korean: '두부', english: 'tofu' },
  { korean: '두부찌개', english: 'tofu soup' },
  { korean: '둘', english: '2' },
  { korean: '둘째', english: 'second, the second of~' },
  { korean: '뒤', english: 'rear, back' },
  { korean: '뒤쪽', english: 'behind, back, towards the rear' },
  { korean: '드라마', english: 'drama' },
  { korean: '드리다', english: 'give' },
  { korean: '드시다', english: 'eat (honorific form)' },
  { korean: '듣기', english: 'listening, hearing' },
  { korean: '듣다', english: 'listen' },
  { korean: '들', english: 'field, ~s,' },
  { korean: '들다', english: 'hold, enter' },
  { korean: '들어가다', english: 'go in, enter' },
  { korean: '들어오다', english: 'come in, enter' },
  { korean: '등', english: 'etc, back' },
  { korean: '등산', english: 'hiking, mountain-climbing' },
  { korean: '등산복', english: 'mountaineering clothing' },
  { korean: '등산화', english: 'hiking boots, climbing shoes' },
  { korean: '디브이디', english: 'DVD' },
  { korean: '디자인', english: 'design' },
  { korean: '따뜻하다', english: 'warm' },
  { korean: '따라가다', english: 'follow' },
  { korean: '따라오다', english: 'come with, follow' },
  { korean: '따로', english: 'separately' },
  { korean: '따르다', english: 'follow' },
  { korean: '딸', english: 'daughter' },
  { korean: '딸기', english: 'strawberry' },
  { korean: '땀', english: 'sweat' },
  { korean: '때', english: 'time' },
  { korean: '때문', english: 'because, for ~, so~' },
  { korean: '떠나다', english: 'leave' },
  { korean: '떠들다', english: 'chatter, make a noise' },
  { korean: '떡', english: 'rice cake' },
  { korean: '떡국', english: 'rice cake soup' },
  { korean: '떡볶이', english: 'Toppogi' },
  { korean: '떨어지다', english: 'drop' },
  { korean: '또', english: 'in addition, again' },
  { korean: '또는', english: 'or' },
  { korean: '똑같다', english: 'same' },
  { korean: '똑바로', english: 'upright, straight' },
  { korean: '뛰다', english: 'run' },
  { korean: '뜨겁다', english: 'hot' },
  { korean: '뜨다', english: 'rise, open (the eyes)' },
  { korean: '뜻', english: 'meaning' },
  { korean: '라디오', english: 'radio' },
  { korean: '라면', english: 'ramen' },
  { korean: '러시아', english: 'Russia' },
  { korean: '로션', english: 'skin lotion' },
  { korean: '마늘', english: 'garlic' },
  { korean: '마르다', english: 'dry' },
  { korean: '마리', english: '~ animal(s), ~ head(s)' },
  { korean: '마시다', english: 'drink' },
  { korean: '마음', english: 'mind, feeling' },
  { korean: '마지막', english: 'last' },
  { korean: '마치다', english: 'finish, end' },
  { korean: '마흔', english: '40' },
  { korean: '막히다', english: 'be blocked, be clogged' },
  { korean: '만', english: 'only, ten thousand' },
  { korean: '만나다', english: 'meet' },
  { korean: '만두', english: 'dumpling' },
  { korean: '만들다', english: 'make, create' },
  { korean: '만일', english: 'if, should' },
  { korean: '만지다', english: 'touch' },
  { korean: '만화', english: 'comic book, cartoon' },
  { korean: '많다', english: 'many' },
  { korean: '많이', english: 'a lot of, many' },
  { korean: '말', english: 'word, talk' },
  { korean: '말씀', english: 'words, remarks' },
  { korean: '말씀하다', english: 'talk' },
  { korean: '말하기', english: 'speaking' },
  { korean: '말하다', english: 'say, talk' },
  { korean: '맑다', english: 'clear, clean' },
  { korean: '맛', english: 'flavor, taste' },
  { korean: '맛없다', english: 'not delicious' },
  { korean: '맛있다', english: 'delicious' },
  { korean: '맞다', english: 'right, fit, correct' },
  { korean: '맞습니다', english: "That's right." },
  { korean: '맞아요', english: "That's right." },
  { korean: '맞은편', english: 'across, the other side, opposite' },
  { korean: '매다', english: 'tie' },
  { korean: '매우', english: 'extremely, very' },
  { korean: '매일', english: 'everyday' },
  { korean: '매주', english: 'every week' },
  { korean: '맥주', english: 'beer' },
  { korean: '맵다', english: 'spicy' },
  { korean: '머리', english: 'head, hair' },
  { korean: '먹다', english: 'eat' },
  { korean: '먼저', english: 'first, first of all, before' },
  { korean: '멀다', english: 'far, distant, long' },
  { korean: '멋있다', english: 'cool, nice' },
  { korean: '메뉴', english: 'menu' },
  { korean: '메다', english: 'shoulder, carry' },
  { korean: '메모', english: 'memo' },
  { korean: '메시지', english: 'message' },
  { korean: '멕시코', english: 'Mexico' },
  { korean: '며칠', english: 'a few days, what date' },
  { korean: '면도', english: 'razor, shaving' },
  { korean: '명', english: '~ person(s)' },
  { korean: '명절', english: 'holidays, annual events' },
  { korean: '몇', english: 'a few, a number of' },
  { korean: '모두', english: 'all, everyone' },
  { korean: '모레', english: 'the day after tomorrow' },
  { korean: '모르겠습니다', english: 'I don\'t know.' },
  { korean: '모르다', english: 'do not know' },
  { korean: '모시다', english: 'take you, serve you (honorific form)' },
  { korean: '모양', english: 'shape, form, style' },
  { korean: '모으다', english: 'collect, gather' },
  { korean: '모이다', english: 'gather, get together' },
  { korean: '모임', english: 'meeting, gathering' },
  { korean: '모자', english: 'hat' },
  { korean: '목', english: 'neck, throat' },
  { korean: '목걸이', english: 'necklace' },
  { korean: '목소리', english: 'voice' },
  { korean: '목요일', english: 'Thursday' },
  { korean: '목욕', english: 'bath, bathing' },
  { korean: '목욕하다', english: 'take a bath' },
  { korean: '목적', english: 'purpose' },
  { korean: '몸', english: 'body' },
  { korean: '몸살', english: 'sickness, disease that comes from fatigue' },
  { korean: '못하다', english: '~ can not do' },
  { korean: '몽골', english: 'Mongolia' },
  { korean: '무', english: 'radish' },
  { korean: '무겁다', english: 'heavy' },
  { korean: '무궁화', english: 'rose of sharon' },
  { korean: '무료', english: 'free' },
  { korean: '무릎', english: 'knee' },
  { korean: '무리', english: 'swarm, unreasonable' },
  { korean: '무섭다', english: 'scary' },
  { korean: '무슨', english: 'what' },
  { korean: '무엇', english: 'what' },
  { korean: '무엇이', english: 'what' },
  { korean: '무역', english: 'trade' },
  { korean: '무용', english: 'dance' },
  { korean: '무척', english: 'very' },
  { korean: '문', english: 'door, gate' },
  { korean: '문구점', english: 'stationery store' },
  { korean: '문장', english: 'sentence' },
  { korean: '문제', english: 'problem' },
  { korean: '문화', english: 'culture' },
  { korean: '묻다', english: 'ask' },
  { korean: '물', english: 'water' },
  { korean: '물건', english: 'stuff, thing' },
  { korean: '물론', english: 'sure, of course' },
  { korean: '물어보다', english: 'ask' },
  { korean: '뭐', english: 'what' },
  { korean: '미국', english: 'The United States' },
  { korean: '미래', english: 'future' },
  { korean: '미리', english: 'in advance, beforehand' },
  { korean: '미술', english: 'art' },
  { korean: '미술관', english: 'art gallery, art museum' },
  { korean: '미안하다', english: 'sorry' },
  { korean: '미안합니다', english: "I'm sorry." },
  { korean: '미용실', english: 'beauty salon' },
  { korean: '미터', english: 'meter' },
  { korean: '민속촌', english: 'folk village' },
  { korean: '밀가루', english: 'flour' },
  { korean: '밀리다', english: 'be shaved, be pushed' },
  { korean: '밑', english: 'bottom, below' },
  { korean: '바꾸다', english: 'change' },
  { korean: '바뀌다', english: 'be changed' },
  { korean: '바나나', english: 'banana' },
  { korean: '바다', english: 'sea' },
  { korean: '바닷가', english: 'beach' },
  { korean: '바라다', english: 'hope' },
  { korean: '바람', english: 'wind' },
  { korean: '바로', english: 'immediately, soon, just' },
  { korean: '바르다', english: 'right, paint, wear' },
  { korean: '바쁘다', english: 'busy' },
  { korean: '바이올린', english: 'violin' },
  { korean: '바지', english: 'pants' },
  { korean: '박물관', english: 'museum' },
  { korean: '박수', english: 'clap, applause' },
  { korean: '밖', english: 'out, outside' },
  { korean: '반', english: 'half, group' },
  { korean: '반갑다', english: 'nice to meet, happy' },
  { korean: '반갑습니다', english: 'Nice to meet you.' },
  { korean: '반년', english: 'half a year' },
  { korean: '반달', english: 'half-moon' },
  { korean: '반바지', english: 'shorts' },
  { korean: '반지', english: 'ring' },
  { korean: '반찬', english: 'side dish' },
  { korean: '받다', english: 'receive' },
  { korean: '발', english: 'foot, leg' },
  { korean: '발가락', english: 'toe(s)' },
  { korean: '발음', english: 'pronunciation' },
  { korean: '발전', english: 'development' },
  { korean: '발표', english: 'announcement, presentation' },
  { korean: '밝다', english: 'bright' },
  { korean: '밤', english: 'night' },
  { korean: '밥', english: 'rice, meal' },
  { korean: '방', english: 'room' },
  { korean: '방법', english: 'way, method' },
  { korean: '방송', english: 'broadcast' },
  { korean: '방송국', english: 'broadcast stations' },
  { korean: '방학', english: 'vacation' },
  { korean: '배', english: 'ship, stomach, pear' },
  { korean: '배고프다', english: 'hungry' },
  { korean: '배구', english: 'volleyball' },
  { korean: '배달', english: 'delivery' },
  { korean: '배부르다', english: 'be full (I am full.)' },
  { korean: '배우', english: 'actor' },
  { korean: '배우다', english: 'learn' },
  { korean: '배탈', english: 'stomachache' },
  { korean: '백', english: '100' },
  { korean: '백화점', english: 'department store' },
  { korean: '버리다', english: 'abandon, throw away' },
  { korean: '버스', english: 'bus' },
  { korean: '번', english: '~ time(s)' },
  { korean: '번호', english: 'number' },
  { korean: '벌다', english: 'earn, make money' },
  { korean: '벌써', english: 'already' },
  { korean: '벗다', english: 'take off (clothes, shoes)' },
  { korean: '벚꽃', english: 'cherry blossom' },
  { korean: '베이징', english: 'Beijing' },
  { korean: '베트남', english: 'Vietnam' },
  { korean: '벽', english: 'wall' },
  { korean: '변호사', english: 'lawyer' },
  { korean: '별', english: 'star' },
  { korean: '별로', english: 'not really' },
  { korean: '병', english: 'illness, ~ bottle(s)' },
  { korean: '병원', english: 'hospital' },
  { korean: '보내다', english: 'send, spend' },
  { korean: '보다', english: 'see' },
  { korean: '보도', english: 'sidewalk, report' },
  { korean: '보이다', english: 'show, look' },
  { korean: '보통', english: 'usually, normally, in general' },
  { korean: '복숭아', english: 'peach' },
  { korean: '복잡하다', english: 'complicated, crowded' },
  { korean: '볶다', english: 'fry' },
  { korean: '볶음밥', english: 'fried rice' },
  { korean: '볼펜', english: 'ballpoint pen' },
  { korean: '봄', english: 'spring' },
  { korean: '봉지', english: 'bag' },
  { korean: '봉투', english: 'envelope' },
  { korean: '뵙다', english: 'meet' },
  { korean: '부동산', english: 'real estate' },
  { korean: '부드럽다', english: 'soft, friendly' },
  { korean: '부르다', english: 'call, sing' },
  { korean: '부모', english: 'parents' },
  { korean: '부부', english: 'couple, husband and wife, married couple' },
  { korean: '부산', english: 'Busan' },
  { korean: '부업', english: 'sideline' },
  { korean: '부엌', english: 'kitchen' },
  { korean: '부인', english: 'wife, Mrs.' },
  { korean: '부장', english: 'director' },
  { korean: '부지런하다', english: 'diligent' },
  { korean: '부치다', english: 'send, fry, transmit' },
  { korean: '부탁', english: 'request, please' },
  { korean: '부탁하다', english: 'beg, ask' },
  { korean: '북쪽', english: 'North' },
  { korean: '분', english: '~ person(s), ~ minute(s)' },
  { korean: '불', english: 'fire, electrical light' },
  { korean: '불고기', english: 'Bulgogi, grilled meat' },
  { korean: '불다', english: 'blow (wind or whistle, musical instruments, etc.)' },
  { korean: '불편하다', english: 'uncomfortable, inconvenient' },
  { korean: '붓다', english: 'pour' },
  { korean: '붙다', english: 'stick, pass a test' },
  { korean: '붙이다', english: 'attach, stick' },
  { korean: '브라질', english: 'Brazil' },
  { korean: '블라우스', english: 'blouse' },
  { korean: '비', english: 'rain' },
  { korean: '비누', english: 'soap' },
  { korean: '비디오', english: 'video' },
  { korean: '비밀', english: 'secret' },
  { korean: '비빔밥', english: 'Bibimbap, mixed rice' },
  { korean: '비슷하다', english: 'similar, like' },
  { korean: '비싸다', english: 'expensive' },
  { korean: '비행기', english: 'airplane' },
  { korean: '비행장', english: 'airfield, airport' },
  { korean: '빌딩', english: 'building' },
  { korean: '빌리다', english: 'borrow, lend' },
  { korean: '빠르다', english: 'fast' },
  { korean: '빨간색', english: 'red color' },
  { korean: '빨갛다', english: 'red' },
  { korean: '빨다', english: 'suck, do laundry' },
  { korean: '빨래', english: 'laundry, wash' },
  { korean: '빨리', english: 'quickly' },
  { korean: '빵', english: 'bread' },
  { korean: '빵집', english: 'bakery' },
  { korean: '빼다', english: 'remove, pull, pull out' },
  { korean: '뿐', english: 'only' },
  { korean: '사', english: '4' },
  { korean: '사거리', english: 'intersection, four corners' },
  { korean: '사계절', english: 'four seasons' },
  { korean: '사고', english: 'accident' },
  { korean: '사과', english: 'apple' },
  { korean: '사다', english: 'buy' },
  { korean: '사람', english: 'person, man' },
  { korean: '사랑', english: 'love' },
  { korean: '사랑하다', english: 'love' },
  { korean: '사례', english: 'case, example' },
  { korean: '사무실', english: 'office' },
  { korean: '사물', english: 'object, thing' },
  { korean: '사십', english: '40' },
  { korean: '사업가', english: 'entrepreneur, businessman' },
  { korean: '사용하다', english: 'use' },
  { korean: '사원', english: 'temple, employee' },
  { korean: '사월', english: 'April' },
  { korean: '사이', english: 'between, while' },
  { korean: '사이다', english: 'cider' },
  { korean: '사이즈', english: 'size' },
  { korean: '사인하다', english: 'sign' },
  { korean: '사장', english: 'CEO, the president' },
  { korean: '사전', english: 'dictionary' },
  { korean: '사진', english: 'picture, photo' },
  { korean: '사진기', english: 'camera' },
  { korean: '사촌', english: 'cousin' },
  { korean: '사탕', english: 'candy' },
  { korean: '사흘', english: '3 days' },
  { korean: '산', english: 'mountain' },
  { korean: '산책', english: 'walk' },
  { korean: '살', english: 'flesh, ~ year(s) old' },
  { korean: '살다', english: 'live' },
  { korean: '삼', english: '3' },
  { korean: '삼거리', english: 'intersection, three-way intersection' },
  { korean: '삼계탕', english: 'Samgyetang' },
  { korean: '삼십', english: '30' },
  { korean: '삼월', english: 'March' },
  { korean: '삼촌', english: 'paternal uncle' },
  { korean: '상관', english: 'relation' },
  { korean: '상자', english: 'box' },
  { korean: '상처', english: 'wound, scratch' },
  { korean: '상품', english: 'product' },
  { korean: '새', english: 'bird, new' },
  { korean: '새로', english: 'newly' },
  { korean: '새벽', english: 'dawn, late at night, early morning' },
  { korean: '새우', english: 'shrimp' },
  { korean: '색', english: 'color' },
  { korean: '색깔', english: 'color' },
  { korean: '샌드위치', english: 'sandwich' },
  { korean: '생각', english: 'thinking, thought' },
  { korean: '생각되다', english: 'be considered, it seems~' },
  { korean: '생각하다', english: 'think' },
  { korean: '생기다', english: 'form, arise' },
  { korean: '생선', english: 'fish' },
  { korean: '생신', english: 'birthday (honorific form)' },
  { korean: '생일', english: 'birthday' },
  { korean: '생활', english: 'life' },
  { korean: '샤워하다', english: 'take a shower' },
  { korean: '샴푸', english: 'shampoo' },
  { korean: '서다', english: 'stand' },
  { korean: '서로', english: 'each other, both' },
  { korean: '서류', english: 'document' },
  { korean: '서른', english: '30' },
  { korean: '서비스', english: 'service' },
  { korean: '서양', english: 'western, west' },
  { korean: '서울', english: 'Seoul' },
  { korean: '서울역', english: 'Seoul station' },
  { korean: '서점', english: 'bookstore' },
  { korean: '서쪽', english: 'west, western' },
  { korean: '선물', english: 'gift, present' },
  { korean: '선배', english: 'elder, senior' },
  { korean: '선생님', english: 'teacher' },
  { korean: '선수', english: 'player' },
  { korean: '선택하다', english: 'choose, select' },
  { korean: '선풍기', english: 'fan' },
  { korean: '설거지', english: 'washing dishes, dish-washing' },
  { korean: '설날', english: 'Lunar New Year' },
  { korean: '설렁탕', english: 'Seolleongtang' },
  { korean: '설명', english: 'explanation, description' },
  { korean: '설명하다', english: 'explain' },
  { korean: '설악산', english: 'Mt. Seorak' },
  { korean: '설탕', english: 'sugar' },
  { korean: '섬', english: 'island' },
  { korean: '성', english: 'castle, last name' },
  { korean: '성격', english: 'personality' },
  { korean: '성함', english: 'name' },
  { korean: '세계', english: 'world' },
  { korean: '세수하다', english: 'wash' },
  { korean: '세우다', english: 'set up, formulate' },
  { korean: '세일하다', english: 'have a sale' },
  { korean: '세탁기', english: 'washing machine' },
  { korean: '세탁소', english: 'dry cleaners, laundromat' },
  { korean: '센터', english: 'center' },
  { korean: '센티미터', english: 'centimeter' },
  { korean: '셋', english: '3' },
  { korean: '셋째', english: 'third' },
  { korean: '소', english: 'small, cow' },
  { korean: '소개', english: 'introduction' },
  { korean: '소개하다', english: 'introduce' },
  { korean: '소고기', english: 'beef' },
  { korean: '소금', english: 'salt' },
  { korean: '소리', english: 'sound, voice' },
  { korean: '소설', english: 'novel' },
  { korean: '소설가', english: 'novelist' },
  { korean: '소식', english: 'news' },
  { korean: '소파', english: 'sofa' },
  { korean: '소포', english: 'parcel' },
  { korean: '소풍', english: 'picnic, trip' },
  { korean: '소화제', english: 'peptic, digestive' },
  { korean: '속', english: 'inside' },
  { korean: '손', english: 'hand' },
  { korean: '손가락', english: 'finger' },
  { korean: '손님', english: 'customer' },
  { korean: '손수건', english: 'handkerchief' },
  { korean: '송이', english: 'bunch, flower, cluster' },
  { korean: '쇼핑', english: 'shopping' },
  { korean: '수건', english: 'towel, washcloth' },
  { korean: '수도', english: 'capital, water supply' },
  { korean: '수돗물', english: 'tap water' },
  { korean: '수박', english: 'watermelon' },
  { korean: '수술하다', english: 'operate on for' },
  { korean: '수업', english: 'class, lesson' },
  { korean: '수영', english: 'swimming' },
  { korean: '수영복', english: 'swimsuit' },
  { korean: '수영장', english: 'swimming pool' },
  { korean: '수요일', english: 'Wednesday' },
  { korean: '수저', english: 'chopsticks and a spoon' },
  { korean: '수첩', english: 'note, notebook' },
  { korean: '수학', english: 'mathematics' },
  { korean: '숙제', english: 'homework' },
  { korean: '순서', english: 'order, turn' },
  { korean: '숟가락', english: 'spoon' },
  { korean: '술', english: 'alcohol, liquor' },
  { korean: '쉬다', english: 'rest' },
  { korean: '쉰', english: '50' },
  { korean: '쉽다', english: 'easy' },
  { korean: '슈퍼마켓', english: 'supermarket' },
  { korean: '스물', english: '20' },
  { korean: '스웨터', english: 'sweater' },
  { korean: '스케이트', english: 'skate' },
  { korean: '스키', english: 'ski, skiing' },
  { korean: '스키장', english: 'ski resort' },
  { korean: '스타', english: 'star' },
  { korean: '스타킹', english: 'stockings' },
  { korean: '스트레스', english: 'stress' },
  { korean: '스페인어', english: 'Spanish' },
  { korean: '스포츠', english: 'sport' },
  { korean: '슬퍼하다', english: 'sorrow, mourn' },
  { korean: '슬프다', english: 'sad' },
  { korean: '습관', english: 'habit' },
  { korean: '시', english: 'city, time' },
  { korean: '시간', english: 'time' },
  { korean: '시간표', english: 'schedule, timetable' },
  { korean: '시계', english: 'clock' },
  { korean: '시골', english: 'countryside' },
  { korean: '시끄럽다', english: 'noisy' },
  { korean: '시내', english: 'downtown, city, stream' },
  { korean: '시다', english: 'sour' },
  { korean: '시디', english: 'CD' },
  { korean: '시민', english: 'citizen' },
  { korean: '시설', english: 'facility' },
  { korean: '시외', english: 'suburbs' },
  { korean: '시원하다', english: 'cool, refresh' },
  { korean: '시월', english: 'October' },
  { korean: '시작', english: 'start' },
  { korean: '시작되다', english: 'begin' },
  { korean: '시작하다', english: 'start, begin' },
  { korean: '시장', english: 'market' },
  { korean: '시청', english: 'city hall' },
  { korean: '시키다', english: 'make someone do, order' },
  { korean: '시험', english: 'exam, test' },
  { korean: '식당', english: 'restaurant, cafeteria' },
  { korean: '식사', english: 'meal' },
  { korean: '식탁', english: 'table' },
  { korean: '신', english: 'god, new' },
  { korean: '신다', english: 'put on, wear' },
  { korean: '신문', english: 'newspaper' },
  { korean: '신발', english: 'shoes, footwear' },
  { korean: '신청서', english: 'application forms' },
  { korean: '신청하다', english: 'put in for, apply for' },
  { korean: '실례', english: 'excuse' },
  { korean: '실례하다', english: 'be excused' },
  { korean: '실수', english: 'mistake, failure' },
  { korean: '싫다', english: 'hate' },
  { korean: '싫어하다', english: 'dislike, hate' },
  { korean: '심하다', english: 'severe, terrible' },
  { korean: '십', english: '10' },
  { korean: '십이월', english: 'December' },
  { korean: '십일월', english: 'November' },
  { korean: '싱겁다', english: 'not salty' },
  { korean: '싶다', english: 'want' },
  { korean: '싸다', english: 'cheap, wrap' },
  { korean: '싸우다', english: 'fight' },
  { korean: '쌀', english: 'rice' },
  { korean: '쌀밥', english: 'cooked rice' },
  { korean: '쌓이다', english: 'stack up, pile up' },
  { korean: '썰다', english: 'chop, cut' },
  { korean: '쓰기', english: 'writing, dictation' },
  { korean: '쓰다', english: 'write, use, wear (glasses)' },
  { korean: '쓰레기', english: 'garbage' },
  { korean: '쓰이다', english: 'be written, be used' },
  { korean: '씨', english: 'seed, Mr. ~' },
  { korean: '씩', english: 'each, every, per' },
  { korean: '씹다', english: 'chew, bite' },
  { korean: '씻다', english: 'wash' },
  { korean: '아가씨', english: 'Miss, daughter' },
  { korean: '아기', english: 'baby, toddler' },
  { korean: '아까', english: 'earlier, while ago' },
  { korean: '아내', english: 'wife' },
  { korean: '아뇨', english: 'no' },
  { korean: '아니다', english: 'no' },
  { korean: '아니오', english: 'no' },
  { korean: '아니요', english: 'no' },
  { korean: '아들', english: 'son' },
  { korean: '아랍어', english: 'Arabic' },
  { korean: '아래', english: 'bottom, under' },
  { korean: '아름답다', english: 'beautiful' },
  { korean: '아마', english: 'maybe, perhaps' },
  { korean: '아무', english: 'any' },
  { korean: '아버님', english: 'father' },
  { korean: '아버지', english: 'father' },
  { korean: '아빠', english: 'dad' },
  { korean: '아시아', english: 'Asia' },
  { korean: '아이', english: 'child' },
  { korean: '아이스크림', english: 'ice cream' },
  { korean: '아저씨', english: 'uncle, mister' },
  { korean: '아주', english: 'very, completely' },
  { korean: '아주머니', english: 'old lady, madame, aunt' },
  { korean: '아줌마', english: 'old lady, madame, aunt' },
  { korean: '아직', english: 'yet, still' },
  { korean: '아침', english: 'morning, breakfast' },
  { korean: '아침밥', english: 'breakfast' },
  { korean: '아침식사', english: 'breakfast' },
  { korean: '아파트', english: 'apartment, mansion' },
  { korean: '아프다', english: 'painful, sick' },
  { korean: '아프리카', english: 'Africa' },
  { korean: '아홉', english: '9' },
  { korean: '아흔', english: '90' },
  { korean: '악기', english: 'musical instrument' },
  { korean: '안', english: 'within, not ~' },
  { korean: '안경', english: 'glasses' },
  { korean: '안내하다', english: 'guide, invite' },
  { korean: '안녕하세요', english: 'hi, hello' },
  { korean: '안녕하십니까', english: 'hello' },
  { korean: '안다', english: 'embrace, cradle' },
  { korean: '안전하다', english: 'safe' },
  { korean: '앉다', english: 'sit' },
  { korean: '알다', english: 'know' },
  { korean: '알리다', english: 'inform' },
  { korean: '알맞다', english: 'fit, appropriate' },
  { korean: '알았습니다', english: 'I understood.' },
  { korean: '앞', english: 'front, previous' },
  { korean: '애', english: 'child' },
  { korean: '액세서리', english: 'accessory' },
  { korean: '야구', english: 'baseball' },
  { korean: '야채', english: 'vegetable' },
  { korean: '약', english: 'about, medicine' },
  { korean: '약간', english: 'slightly, a little' },
  { korean: '약국', english: 'pharmacy' },
  { korean: '약사', english: 'pharmacist' },
  { korean: '약속', english: 'appointment, promise' },
  { korean: '얇다', english: 'thin' },
  { korean: '양', english: 'amount, sheep' },
  { korean: '양말', english: 'socks' },
  { korean: '양복', english: 'suit' },
  { korean: '양식', english: 'form, western style' },
  { korean: '양파', english: 'onion' },
  { korean: '얘기하다', english: 'talk' },
  { korean: '어깨', english: 'shoulder' },
  { korean: '어느', english: 'which, how' },
  { korean: '어둡다', english: 'dark' },
  { korean: '어디', english: 'where' },
  { korean: '어떤', english: 'which, what' },
  { korean: '어떻게', english: 'how' },
  { korean: '어떻다', english: 'how' },
  { korean: '어떻습니까?', english: 'How is it?' },
  { korean: '어렵다', english: 'difficult' },
  { korean: '어른', english: 'adult' },
  { korean: '어리다', english: 'young' },
  { korean: '어린이', english: 'child' },
  { korean: '어머', english: 'oh, well' },
  { korean: '어머니', english: 'mother' },
  { korean: '어머님', english: 'mother' },
  { korean: '어서', english: 'hurry, quickly' },
  { korean: '어울리다', english: 'look good on, befit' },
  { korean: '어저께', english: 'yesterday' },
  { korean: '어제', english: 'yesterday' },
  { korean: '어젯밤', english: 'last night' },
  { korean: '언니', english: 'sister (as seen from the younger sister)' },
  { korean: '언제', english: 'when' },
  { korean: '언제나', english: 'always, anytime' },
  { korean: '얼굴', english: 'face' },
  { korean: '얼마나', english: 'how much' },
  { korean: '얼음', english: 'ice' },
  { korean: '엄마', english: 'mom' },
  { korean: '없다', english: 'none, no, not' },
  { korean: '없이', english: 'without' },
  { korean: '에어컨', english: 'air conditioner' },
  { korean: '엔', english: 'yen' },
  { korean: '엘리베이터', english: 'elevator' },
  { korean: '여권', english: 'passport' },
  { korean: '여기', english: 'here' },
  { korean: '여기저기', english: 'here and there' },
  { korean: '여덟', english: '8' },
  { korean: '여동생', english: 'younger sister' },
  { korean: '여든', english: '80' },
  { korean: '여러', english: 'various, many' },
  { korean: '여러가지', english: 'several, various' },
  { korean: '여러분', english: 'everyone, ladies and gentlemen' },
  { korean: '여름', english: 'summer' },
  { korean: '여보세요', english: 'hello' },
  { korean: '여섯', english: '6' },
  { korean: '여자', english: 'woman' },
  { korean: '여학생', english: 'female student' },
  { korean: '여행', english: 'travel' },
  { korean: '여행사', english: 'travel agency, travel firm' },
  { korean: '역', english: 'station' },
  { korean: '역사', english: 'history' },
  { korean: '연락처', english: 'contact information' },
  { korean: '연세', english: 'age (honorific form)' },
  { korean: '연습', english: 'practice' },
  { korean: '연습하다', english: 'practice' },
  { korean: '연예인', english: 'celebrity' },
  { korean: '연필', english: 'pencil' },
  { korean: '연휴', english: 'consecutive holidays' },
  { korean: '열', english: '10' },
  { korean: '열다', english: 'open' },
  { korean: '열리다', english: 'be opened' },
  { korean: '열쇠', english: 'key' },
  { korean: '열심히', english: 'hard, enthusiastic' },
  { korean: '열차', english: 'train' },
  { korean: '엽서', english: 'postcard' },
  { korean: '영', english: 'spirit, zero' },
  { korean: '영국', english: 'The United Kingdom' },
  { korean: '영상', english: 'video' },
  { korean: '영어', english: 'English' },
  { korean: '영어회화', english: 'English conversation' },
  { korean: '영하', english: 'minus, below zero' },
  { korean: '영화', english: 'movie' },
  { korean: '영화관', english: 'movie theater' },
  { korean: '영화배우', english: 'movie star' },
  { korean: '영화표', english: 'movie ticket' },
  { korean: '옆', english: 'side' },
  { korean: '예', english: 'yes' },
  { korean: '예문', english: 'example, model sentence' },
  { korean: '예쁘다', english: 'pretty, beautiful' },
  { korean: '예순', english: '60' },
  { korean: '예약', english: 'reservation' },
  { korean: '옛날', english: 'a long ago, olden days' },
  { korean: '오', english: '5' },
  { korean: '오늘', english: 'today' },
  { korean: '오다', english: 'come' },
  { korean: '오래', english: 'long, much' },
  { korean: '오래간만', english: 'after a long time' },
  { korean: '오래간만입니다', english: 'Long time no see.' },
  { korean: '오랜만', english: 'after a long time' },
  { korean: '오랜만에', english: 'after a long time' },
  { korean: '오랫동안', english: 'for a long time' },
  { korean: '오렌지', english: 'orange' },
  { korean: '오르다', english: 'climb' },
  { korean: '오른쪽', english: 'right side, right' },
  { korean: '오리', english: 'duck' },
  { korean: '오빠', english: 'brother (as seen from the younger sister)' },
  { korean: '오십', english: '50' },
  { korean: '오월', english: 'May' },
  { korean: '오이', english: 'cucumber' },
  { korean: '오전', english: 'morning, a.m.' },
  { korean: '오징어', english: 'squid' },
  { korean: '오후', english: 'afternoon' },
  { korean: '올라가다', english: 'go up' },
  { korean: '올라오다', english: 'come up' },
  { korean: '올려놓다', english: 'put on, place' },
  { korean: '올림픽', english: 'olympic' },
  { korean: '올해', english: 'this year' },
  { korean: '옮기다', english: 'move, transfer, translate' },
  { korean: '옷', english: 'dress, clothes' },
  { korean: '옷가게', english: 'clothing store' },
  { korean: '옷장', english: 'closet' },
  { korean: '와이셔츠', english: 'shirt' },
  { korean: '왜', english: 'why' },
  { korean: '왜냐하면', english: 'because' },
  { korean: '외국', english: 'foreign country' },
  { korean: '외국어', english: 'foreign language' },
  { korean: '외국인', english: 'foreigner' },
  { korean: '외롭다', english: 'lonely' },
  { korean: '외삼촌', english: 'maternal uncle' },
  { korean: '외숙모', english: 'maternal aunt' },
  { korean: '외출하다', english: 'go out' },
  { korean: '외할머니', english: 'maternal grandmother' },
  { korean: '외할아버지', english: 'maternal grandfather' },
  { korean: '왼쪽', english: 'left' },
  { korean: '요금', english: 'fee' },
  { korean: '요르단', english: 'Jordan' },
  { korean: '요리', english: 'cooking, cuisine' },
  { korean: '요일', english: 'day of the week' },
  { korean: '요즘', english: 'nowadays, around this time, lately' },
  { korean: '우리', english: 'we, us' },
  { korean: '우리나라', english: 'our country, South Korea' },
  { korean: '우산', english: 'umbrella' },
  { korean: '우선', english: 'first' },
  { korean: '우유', english: 'milk' },
  { korean: '우체국', english: 'post office' },
  { korean: '우표', english: 'stamp' },
  { korean: '운동', english: 'exercise' },
  { korean: '운동복', english: 'sportswear, gym clothes' },
  { korean: '운동선수', english: 'athlete' },
  { korean: '운동장', english: 'playground, athletic field' },
  { korean: '운동하다', english: 'exercise' },
  { korean: '운동화', english: 'sports shoes' },
  { korean: '운전하다', english: 'drive' },
  { korean: '울다', english: 'cry' },
  { korean: '울리다', english: 'make cry, chime' },
  { korean: '움직이다', english: 'move' },
  { korean: '웃기다', english: 'funny, make someone laugh' },
  { korean: '웃다', english: 'laugh' },
  { korean: '원', english: 'won (currency units of Korea)' },
  { korean: '원피스', english: 'one-piece dress' },
  { korean: '원하다', english: 'want, wish, desire' },
  { korean: '월', english: 'month' },
  { korean: '월급', english: 'monthly salary' },
  { korean: '월드컵', english: 'world cup' },
  { korean: '월세', english: 'monthly rent' },
  { korean: '월요일', english: 'Monday' },
  { korean: '웬일', english: 'for some reason, What was it?' },
  { korean: '위', english: 'top, up' },
  { korean: '위치', english: 'location, position' },
  { korean: '위하다', english: 'for, in favor of, for the sake of' },
  { korean: '위험하다', english: 'dangerous' },
  { korean: '유럽', english: 'Europe' },
  { korean: '유리', english: 'glass' },
  { korean: '유명하다', english: 'famous' },
  { korean: '유월', english: 'June' },
  { korean: '유학', english: 'study abroad' },
  { korean: '유학생', english: 'foreign student, international student' },
  { korean: '유행', english: 'trend' },
  { korean: '육', english: '6' },
  { korean: '육십', english: '60' },
  { korean: '은행', english: 'bank' },
  { korean: '은행원', english: 'bank clerk' },
  { korean: '음료수', english: 'drink, soft drink' },
  { korean: '음반', english: 'record' },
  { korean: '음식', english: 'food, cooking' },
  { korean: '음악', english: 'music' },
  { korean: '음악가', english: 'musician' },
  { korean: '응', english: 'Yeah (answer)' },
  { korean: '의미', english: 'meaning' },
  { korean: '의사', english: 'doctor' },
  { korean: '의자', english: 'chair' },
  { korean: '이', english: 'this, tooth, 2' },
  { korean: '이거', english: 'this' },
  { korean: '이것', english: 'this' },
  { korean: '이곳', english: 'this place, here' },
  { korean: '이따가', english: 'later' },
  { korean: '이런', english: 'this, such ~' },
  { korean: '이렇게', english: 'like this, so, in this way' },
  { korean: '이렇다', english: 'like this' },
  { korean: '이름', english: 'name' },
  { korean: '이메일', english: 'e-mail' },
  { korean: '이모', english: 'maternal aunt' },
  { korean: '이모부', english: 'maternal uncle' },
  { korean: '이번', english: 'this time' },
  { korean: '이분', english: 'this person' },
  { korean: '이사', english: 'move, moving' },
  { korean: '이상', english: 'more than, strange' },
  { korean: '이상하다', english: 'strange, funny, weird' },
  { korean: '이십', english: '20' },
  { korean: '이야기', english: 'story' },
  { korean: '이야기하다', english: 'talk' },
  { korean: '이용', english: 'usage' },
  { korean: '이용하다', english: 'use' },
  { korean: '이월', english: 'February' },
  { korean: '이유', english: 'reason' },
  { korean: '이제', english: 'now' },
  { korean: '이집트', english: 'Egypt' },
  { korean: '이쪽', english: 'this way, here, this person' },
  { korean: '이틀', english: 'two days' },
  { korean: '이해', english: 'understanding' },
  { korean: '이해하다', english: 'understand' },
  { korean: '인', english: 'sign, ~ person(s)' },
  { korean: '인구', english: 'population' },
  { korean: '인기', english: 'popularity' },
  { korean: '인기스타', english: 'popular star' },
  { korean: '인도', english: 'India' },
  { korean: '인사', english: 'greetings' },
  { korean: '인사하다', english: 'greet' },
  { korean: '인삼', english: 'ginseng' },
  { korean: '인상', english: 'impression' },
  { korean: '인천', english: 'Incheon' },
  { korean: '인터넷', english: 'internet' },
  { korean: '인터뷰하다', english: 'interview' },
  { korean: '인형', english: 'doll' },
  { korean: '일', english: 'work, 1, day' },
  { korean: '일곱', english: '7' },
  { korean: '일기', english: 'diary' },
  { korean: '일기예보', english: 'weather forecast' },
  { korean: '일본', english: 'Japan' },
  { korean: '일본드라마', english: 'Japanese drama' },
  { korean: '일본말', english: 'Japanese language' },
  { korean: '일본사람', english: 'Japanese people' },
  { korean: '일본어', english: 'Japanese language' },
  { korean: '일본요리', english: 'Japanese food' },
  { korean: '일상생활', english: 'everyday life' },
  { korean: '일식', english: 'Japanese style, Japanese food' },
  { korean: '일어나다', english: 'rise, stand, occur' },
  { korean: '일어서다', english: 'get up, stand up' },
  { korean: '일요일', english: 'Sunday' },
  { korean: '일월', english: 'January' },
  { korean: '일주일', english: 'one week' },
  { korean: '일찍', english: 'early' },
  { korean: '일하다', english: 'work' },
  { korean: '일흔', english: '70' },
  { korean: '읽기', english: 'reading' },
  { korean: '읽다', english: 'read' },
  { korean: '잃다', english: 'lose' },
  { korean: '잃어버리다', english: 'lose' },
  { korean: '입', english: 'mouth' },
  { korean: '입구', english: 'entrance' },
  { korean: '입다', english: 'put on, wear' },
  { korean: '입원하다', english: 'hospitalize' },
  { korean: '입학', english: 'admission' },
  { korean: '있다', english: 'have, there' },
  { korean: '잊다', english: 'forget' },
  { korean: '잊어버리다', english: 'forget' },
  { korean: '자', english: 'character, Here we go.' },
  { korean: '자기', english: 'myself, own' },
  { korean: '자다', english: 'sleep' },
  { korean: '자동차', english: 'car, automobile' },
  { korean: '자동차회사', english: 'car company' },
  { korean: '자료', english: 'material, document' },
  { korean: '자르다', english: 'cut' },
  { korean: '자리', english: 'seat, location' },
  { korean: '자신', english: 'myself, own' },
  { korean: '자연', english: 'nature' },
  { korean: '자유', english: 'freedom' },
  { korean: '자장면', english: 'Jajangmyeon' },
  { korean: '자전거', english: 'bicycle' },
  { korean: '자주', english: 'often' },
  { korean: '작년', english: 'last year' },
  { korean: '작다', english: 'small' },
  { korean: '작은아버지', english: 'uncle' },
  { korean: '작은어머니', english: 'aunt' },
  { korean: '잔', english: 'glass, ~ cup(s)' },
  { korean: '잔치', english: 'party, feast' },
  { korean: '잘', english: 'well' },
  { korean: '잘못', english: 'mistake' },
  { korean: '잘생기다', english: 'handsome' },
  { korean: '잘하다', english: 'do well, good at' },
  { korean: '잠', english: 'slumbers, sleep' },
  { korean: '잠깐', english: 'for a while, a little' },
  { korean: '잠시', english: 'for a bit, for a while, a little' },
  { korean: '잠자다', english: 'sleep, go to bed' },
  { korean: '잡다', english: 'catch, grab, hold' },
  { korean: '잡수시다', english: 'eat (honorific form)' },
  { korean: '잡지', english: 'magazine' },
  { korean: '장', english: '~ chapter(s), ~ sheet(s)' },
  { korean: '장갑', english: 'gloves' },
  { korean: '장마', english: 'rainy season' },
  { korean: '장마철', english: 'rainy season' },
  { korean: '장미', english: 'rose' },
  { korean: '장소', english: 'place' },
  { korean: '장점', english: 'advantage' },
  { korean: '재료', english: 'material' },
  { korean: '재미없다', english: 'not funny, uninteresting' },
  { korean: '재미있다', english: 'interesting' },
  { korean: '재킷', english: 'jacket' },
  { korean: '저', english: 'that' },
  { korean: '저거', english: 'that' },
  { korean: '저것', english: 'that' },
  { korean: '저곳', english: 'over there' },
  { korean: '저기', english: 'there, over there' },
  { korean: '저녁', english: 'dinner, evening, night' },
  { korean: '저녁식사', english: 'dinner' },
  { korean: '저렇게', english: 'like that, in that way' },
  { korean: '저분', english: 'that person' },
  { korean: '저쪽', english: 'there, over there' },
  { korean: '저희', english: 'we' },
  { korean: '적', english: 'enemy' },
  { korean: '적다', english: 'be few, write down' },
  { korean: '전', english: 'all, before' },
  { korean: '전공', english: 'major' },
  { korean: '전기자동차', english: 'electric car' },
  { korean: '전자사전', english: 'electronic dictionary' },
  { korean: '전하다', english: 'tell' },
  { korean: '전혀', english: 'not at all' },
  { korean: '전화', english: 'telephone' },
  { korean: '전화기', english: 'telephone' },
  { korean: '전화번호', english: 'phone number' },
  { korean: '절', english: '~ section(s), temple' },
  { korean: '절대', english: 'never, absolutely' },
  { korean: '젊다', english: 'young' },
  { korean: '점', english: 'point' },
  { korean: '점수', english: 'score, point' },
  { korean: '점심', english: 'lunch' },
  { korean: '점심시간', english: 'lunchtime' },
  { korean: '점심식사', english: 'lunch' },
  { korean: '점원', english: 'clerk' },
  { korean: '점퍼', english: 'jacket' },
  { korean: '젓가락', english: 'chopsticks' },
  { korean: '정거장', english: 'station, depot' },
  { korean: '정도', english: 'degree' },
  { korean: '정류장', english: 'station, bus stop' },
  { korean: '정리하다', english: 'straighten out, organize' },
  { korean: '정말', english: 'really, truly' },
  { korean: '정문', english: 'front door, main gate' },
  { korean: '정보', english: 'information' },
  { korean: '정하다', english: 'choose, establish' },
  { korean: '제가', english: 'I' },
  { korean: '제목', english: 'title' },
  { korean: '제일', english: 'most' },
  { korean: '제주도', english: 'Jeju Island' },
  { korean: '조금', english: 'a little' },
  { korean: '조사하다', english: 'investigate' },
  { korean: '조선', english: 'shipbuilding, Korea' },
  { korean: '조선말', english: 'Korean language' },
  { korean: '조선어', english: 'Korean language' },
  { korean: '조심하다', english: 'be careful, warn' },
  { korean: '조용하다', english: 'silent, quiet' },
  { korean: '조용히', english: 'quietly' },
  { korean: '조카', english: 'nephew' },
  { korean: '졸업', english: 'graduation' },
  { korean: '졸업하다', english: 'graduate' },
  { korean: '좀', english: 'a little' },
  { korean: '좀더', english: 'a little more' },
  { korean: '좁다', english: 'narrow' },
  { korean: '종로', english: 'Jong-ro' },
  { korean: '종류', english: 'kind, type' },
  { korean: '종업원', english: 'employee' },
  { korean: '종이', english: 'paper' },
  { korean: '종일', english: 'all day' },
  { korean: '좋다', english: 'good' },
  { korean: '좋아하다', english: 'like' },
  { korean: '죄송하다', english: 'sorry' },
  { korean: '주', english: 'week' },
  { korean: '주다', english: 'give' },
  { korean: '주로', english: 'mainly' },
  { korean: '주말', english: 'weekend' },
  { korean: '주머니', english: 'pocket, pouch' },
  { korean: '주무시다', english: 'sleep, rest' },
  { korean: '주문하다', english: 'order' },
  { korean: '주변', english: 'around' },
  { korean: '주부', english: 'housewife' },
  { korean: '주사', english: 'injection' },
  { korean: '주소', english: 'address' },
  { korean: '주스', english: 'juice' },
  { korean: '주위', english: 'around' },
  { korean: '주인', english: 'owner' },
  { korean: '주차장', english: 'parking lot' },
  { korean: '주차하다', english: 'park' },
  { korean: '주황색', english: 'orange color' },
  { korean: '죽', english: 'bamboo, porridge' },
  { korean: '죽다', english: 'die' },
  { korean: '준비', english: 'preparation' },
  { korean: '준비하다', english: 'prepare' },
  { korean: '줄', english: 'line, column, string' },
  { korean: '줄다', english: 'shrink, decrease' },
  { korean: '중', english: 'medium, during' },
  { korean: '중국', english: 'China' },
  { korean: '중국어', english: 'Chinese' },
  { korean: '중국집', english: 'Chinese restaurant' },
  { korean: '중식', english: 'Chinese cuisine' },
  { korean: '중심', english: 'center' },
  { korean: '중요', english: 'importance' },
  { korean: '중요하다', english: 'important' },
  { korean: '중학교', english: 'middle school, Junior high school' },
  { korean: '중학생', english: 'middle school student' },
  { korean: '즐거워하다', english: 'have fun' },
  { korean: '즐겁다', english: 'fun, be pleasant' },
  { korean: '즐기다', english: 'enjoy, have fun' },
  { korean: '증세', english: 'symptom, medical condition' },
  { korean: '지각', english: 'tardy, being late' },
  { korean: '지갑', english: 'wallet' },
  { korean: '지금', english: 'now' },
  { korean: '지나다', english: 'pass by' },
  { korean: '지난달', english: 'last month' },
  { korean: '지난번', english: 'last time' },
  { korean: '지난주', english: 'last week' },
  { korean: '지내다', english: 'stay, spend, live' },
  { korean: '지다', english: 'lose' },
  { korean: '지도', english: 'map' },
  { korean: '지방', english: 'fat, region' },
  { korean: '지우개', english: 'eraser' },
  { korean: '지키다', english: 'protect' },
  { korean: '지하', english: 'underground' },
  { korean: '지하도', english: 'underpass' },
  { korean: '지하철', english: 'subway' },
  { korean: '지하철역', english: 'subway station' },
  { korean: '직업', english: 'job, profession' },
  { korean: '직원', english: 'employee, staff' },
  { korean: '직장', english: 'workplace' },
  { korean: '직접', english: 'directly, direct' },
  { korean: '진달래', english: 'azalea' },
  { korean: '질', english: 'quality' },
  { korean: '질문', english: 'question' },
  { korean: '질문하다', english: 'ask a question' },
  { korean: '짐', english: 'load, baggage' },
  { korean: '집', english: 'house, shop' },
  { korean: '짓다', english: 'build, create' },
  { korean: '짜다', english: 'salty, make (the plan)' },
  { korean: '짜리', english: 'a value (won coin)' },
  { korean: '짧다', english: 'short' },
  { korean: '쪽', english: 'side, page' },
  { korean: '쯤', english: 'about, around ~' },
  { korean: '찌개', english: 'stew, soup' },
  { korean: '찍다', english: 'pierce, take (a photo), press' },
  { korean: '차', english: 'car, tea' },
  { korean: '차갑다', english: 'cold' },
  { korean: '차다', english: 'kick' },
  { korean: '차리다', english: 'prepare, arrange' },
  { korean: '착하다', english: 'be good, friendly' },
  { korean: '참', english: 'really, very' },
  { korean: '창문', english: 'window' },
  { korean: '찾다', english: 'find, visit' },
  { korean: '찾아가다', english: 'go to visit' },
  { korean: '찾아오다', english: 'come to visit' },
  { korean: '채소', english: 'vegetable' },
  { korean: '책', english: 'book' },
  { korean: '책방', english: 'bookstore' },
  { korean: '책상', english: 'desk' },
  { korean: '책임', english: 'responsibility' },
  { korean: '책장', english: 'bookshelf' },
  { korean: '처음', english: 'first, for the first time' },
  { korean: '처음 뵙겠습니다', english: 'Nice to meet you.' },
  { korean: '천', english: '1000' },
  { korean: '천천히', english: 'slowly' },
  { korean: '철', english: 'iron, season' },
  { korean: '첫', english: 'first' },
  { korean: '첫째', english: 'first' },
  { korean: '청바지', english: 'blue jeans' },
  { korean: '청소기', english: 'vacuum cleaner' },
  { korean: '청소하다', english: 'sweep, clean' },
  { korean: '초', english: '~second(s)' },
  { korean: '초대하다', english: 'invite' },
  { korean: '초등학교', english: 'elementary school' },
  { korean: '초등학생', english: 'elementary student' },
  { korean: '초록색', english: 'green color' },
  { korean: '초콜릿', english: 'chocolate' },
  { korean: '촬영하다', english: 'take a picture' },
  { korean: '최고', english: 'best, the highest' },
  { korean: '추다', english: 'dance' },
  { korean: '추석', english: 'Chusoku (Korean Thanksgiving Day)' },
  { korean: '추억', english: 'memory' },
  { korean: '축구', english: 'football, soccer' },
  { korean: '축제', english: 'festival' },
  { korean: '축하', english: 'celebration' },
  { korean: '축하하다', english: 'celebrate' },
  { korean: '축하합니다', english: 'congratulations' },
  { korean: '출구', english: 'exit' },
  { korean: '출근하다', english: 'go to work' },
  { korean: '출발', english: 'start, departure' },
  { korean: '출발하다', english: 'depart' },
  { korean: '출장', english: 'business trip' },
  { korean: '춤', english: 'dance' },
  { korean: '춤추다', english: 'dance' },
  { korean: '춥다', english: 'cold' },
  { korean: '취미', english: 'hobby' },
  { korean: '취소하다', english: 'cancel' },
  { korean: '취직하다', english: 'get a job' },
  { korean: '층', english: 'layer, ~ floor' },
  { korean: '치과', english: 'dentist, dentistry' },
  { korean: '치료하다', english: 'treat' },
  { korean: '치마', english: 'skirt' },
  { korean: '치약', english: 'toothpaste' },
  { korean: '친구', english: 'friend' },
  { korean: '친절하다', english: 'be kind' },
  { korean: '친척', english: 'relative' },
  { korean: '친하다', english: 'close, familiar' },
  { korean: '칠', english: '7' },
  { korean: '칠십', english: '70' },
  { korean: '칠월', english: 'July' },
  { korean: '칠판', english: 'blackboard' },
  { korean: '침대', english: 'bed' },
  { korean: '칫솔', english: 'toothbrush' },
  { korean: '카드', english: 'card' },
  { korean: '카레', english: 'curry' },
  { korean: '카메라', english: 'camera' },
  { korean: '카페', english: 'cafe, coffee shops' },
  { korean: '칼', english: 'knife, cutlery, swords' },
  { korean: '캐나다', english: 'Canada' },
  { korean: '커피', english: 'coffee' },
  { korean: '커피숍', english: 'coffee shop' },
  { korean: '컴퓨터', english: 'computer, PC' },
  { korean: '컵', english: 'cup' },
  { korean: '케이크', english: 'cake' },
  { korean: '켜다', english: 'turn on (the light, the power, etc.)' },
  { korean: '코', english: 'nose' },
  { korean: '코트', english: 'coat' },
  { korean: '코피', english: 'nosebleed' },
  { korean: '콜라', english: 'Coke' },
  { korean: '콧노래', english: 'humming' },
  { korean: '콧물', english: 'snot, nasal discharge' },
  { korean: '콩', english: 'bean, soy' },
  { korean: '크기', english: 'size' },
  { korean: '크다', english: 'big, large' },
  { korean: '크리스마스', english: 'Christmas' },
  { korean: '큰아버지', english: 'uncle' },
  { korean: '큰어머니', english: 'aunt' },
  { korean: '키', english: 'key, height' },
  { korean: '킬로그램', english: 'kilogram' },
  { korean: '킬로미터', english: 'kilometer' },
  { korean: '타다', english: 'ride, get on' },
  { korean: '타월', english: 'towel' },
  { korean: '탁구', english: 'table tennis' },
  { korean: '태국', english: 'Thailand' },
  { korean: '태권도', english: 'Taekwondo' },
  { korean: '태어나다', english: 'be born' },
  { korean: '태풍', english: 'typhoon' },
  { korean: '택시', english: 'taxi' },
  { korean: '탤런트', english: 'entertainers' },
  { korean: '터미널', english: 'terminal' },
  { korean: '테니스', english: 'tennis' },
  { korean: '테이블', english: 'table' },
  { korean: '텔레비전', english: 'TV' },
  { korean: '토마토', english: 'tomato' },
  { korean: '토요일', english: 'Saturday' },
  { korean: '통', english: 'barrel, ~ package(s)' },
  { korean: '통장', english: 'bank book, (deposit) passbook' },
  { korean: '통하다', english: 'pass, lead' },
  { korean: '퇴근하다', english: 'leave the office' },
  { korean: '특별히', english: 'especially' },
  { korean: '특징', english: 'characteristic, feature' },
  { korean: '특히', english: 'especially, in particular' },
  { korean: '틀다', english: 'turn on (the switch)' },
  { korean: '틀리다', english: 'wrong' },
  { korean: '티셔츠', english: 't-shirt' },
  { korean: '팀', english: 'team' },
  { korean: '파', english: 'wave, green onion' },
  { korean: '파란색', english: 'blue color' },
  { korean: '파랗다', english: 'blue' },
  { korean: '파티', english: 'party' },
  { korean: '팔', english: '8' },
  { korean: '팔다', english: 'sell' },
  { korean: '팔리다', english: 'sell, be sold' },
  { korean: '팔십', english: '80' },
  { korean: '팔월', english: 'August' },
  { korean: '패션', english: 'fashion' },
  { korean: '퍼센트', english: 'percent' },
  { korean: '페이지', english: 'page' },
  { korean: '펜', english: 'pen' },
  { korean: '펴다', english: 'spread, stretch' },
  { korean: '편', english: 'side, episode' },
  { korean: '편지', english: 'letter' },
  { korean: '편하다', english: 'comfortable, easy, convenient' },
  { korean: '평양', english: 'Pyongyang' },
  { korean: '평일', english: 'weekday' },
  { korean: '포도', english: 'grape' },
  { korean: '포장', english: 'packing' },
  { korean: '표', english: 'table, ticket' },
  { korean: '표현', english: 'expression' },
  { korean: '푹', english: 'deeply' },
  { korean: '풀', english: 'pool, grass' },
  { korean: '풀다', english: 'solve' },
  { korean: '프랑스', english: 'France' },
  { korean: '프로그램', english: 'program' },
  { korean: '프린트', english: 'print' },
  { korean: '피', english: 'blood' },
  { korean: '피곤하다', english: 'tired' },
  { korean: '피다', english: 'bloom' },
  { korean: '피아노', english: 'piano' },
  { korean: '피우다', english: 'smoke, bloom' },
  { korean: '피자', english: 'pizza' },
  { korean: '필름', english: 'film' },
  { korean: '필요', english: 'necessity' },
  { korean: '필요하다', english: 'need' },
  { korean: '필통', english: 'pencil case' },
  { korean: '하나', english: '1' },
  { korean: '하늘', english: 'sky' },
  { korean: '하늘색', english: 'sky blue, light blue' },
  { korean: '하다', english: 'do, say' },
  { korean: '하루', english: 'one day' },
  { korean: '하숙', english: 'boarding house, lodging house' },
  { korean: '하숙집', english: 'boarding house, lodging house' },
  { korean: '하얀색', english: 'white color' },
  { korean: '하얗다', english: 'white' },
  { korean: '하지만', english: 'but, however' },
  { korean: '학', english: 'crane' },
  { korean: '학교', english: 'school' },
  { korean: '학기', english: 'semester' },
  { korean: '학년', english: 'grade, school year' },
  { korean: '학생', english: 'student' },
  { korean: '학생증', english: 'student ID card' },
  { korean: '학원', english: 'academy, school' },
  { korean: '한', english: 'one, one of the ~' },
  { korean: '한강', english: 'Han River, Hangang' },
  { korean: '한국', english: 'Korea' },
  { korean: '한국드라마', english: 'Korean drama' },
  { korean: '한국말', english: 'Korean language' },
  { korean: '한국사람', english: 'Korean people' },
  { korean: '한국어', english: 'Korean language' },
  { korean: '한국요리', english: 'Korean cuisine' },
  { korean: '한글', english: 'Hangul' },
  { korean: '한번', english: 'once' },
  { korean: '한복', english: 'Hanbok, Korean traditional clothes' },
  { korean: '한식', english: 'Korean cuisine' },
  { korean: '한자', english: 'Chinese character' },
  { korean: '할머니', english: 'grandmother' },
  { korean: '할아버지', english: 'grandfather' },
  { korean: '할인', english: 'sale, discount' },
  { korean: '함께', english: 'together' },
  { korean: '합격', english: 'pass' },
  { korean: '항상', english: 'always' },
  { korean: '해', english: 'year, sun' },
  { korean: '해외', english: 'overseas' },
  { korean: '해외여행', english: 'overseas trip' },
  { korean: '핸드폰', english: 'cell phone, mobile phone' },
  { korean: '햄버거', english: 'hamburger' },
  { korean: '햇빛', english: 'sunshine, sunlight' },
  { korean: '행복', english: 'happiness' },
  { korean: '행복하다', english: 'happy' },
  { korean: '행사', english: 'event' },
  { korean: '허리', english: 'waist, hip' },
  { korean: '현금', english: 'cash' },
  { korean: '현재', english: 'now, current' },
  { korean: '형', english: 'brother (as seen from the younger brother)' },
  { korean: '형님', english: 'big brother (honorific form)' },
  { korean: '형제', english: 'sibling' },
  { korean: '호', english: 'No. ~' },
  { korean: '호랑이', english: 'tiger' },
  { korean: '호주', english: 'Australia' },
  { korean: '호텔', english: 'hotel' },
  { korean: '혼자', english: 'alone' },
  { korean: '홈페이지', english: 'home page' },
  { korean: '홍차', english: 'black tea' },
  { korean: '화', english: 'anger' },
  { korean: '화가', english: 'artist, painter' },
  { korean: '화나다', english: 'angry' },
  { korean: '화내다', english: 'get angry' },
  { korean: '화요일', english: 'Tuesday' },
  { korean: '화장실', english: 'restroom, toilet, lavatory' },
  { korean: '화장품', english: 'cosmetics' },
  { korean: '화장하다', english: 'makeup' },
  { korean: '확인하다', english: 'confirm, check' },
  { korean: '환영하다', english: 'welcome' },
  { korean: '환자', english: 'patient' },
  { korean: '회사', english: 'company' },
  { korean: '회사원', english: 'employee' },
  { korean: '회색', english: 'grey' },
  { korean: '회의', english: 'conference' },
  { korean: '횡단보도', english: 'crosswalk' },
  { korean: '후', english: 'after' },
  { korean: '후배', english: 'Junior' },
  { korean: '휴가', english: 'vacation, holiday' },
  { korean: '휴대전화', english: 'cell phone, mobile phone' },
  { korean: '휴일', english: 'holiday' },
  { korean: '휴지', english: 'toilet paper' },
  { korean: '휴지통', english: 'trash can' },
  { korean: '흐리다', english: 'cloudy' },
  { korean: '흰색', english: 'white color' },
  { korean: '힘', english: 'power' },
];
